import type { Route, Ticket, Crew, Material } from "@/types/ticket"

export const mockTickets: Ticket[] = [
  {
    id: "235712",
    ticketNumber: "#235712",
    title: "Poste caído/torcido",
    category: "Alumbrado",
    subcategory: "Postes",
    address: "NACION 156 Barrio CENTRO",
    contact: "23443345",
    latitude: -33.3317,
    longitude: -60.2264,
    status: "open",
    priority: "high",
    agent: "alumbrado",
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "235699",
    ticketNumber: "#235699",
    title: "Luminaria quemada",
    category: "Alumbrado",
    subcategory: "Luminarias",
    address: "OLLEROS 364 Barrio 14 DE ABRIL entre calles Lisandro La torre y Bustamante",
    contact: "23445567",
    latitude: -33.3342,
    longitude: -60.2298,
    status: "open",
    priority: "medium",
    agent: "alumbrado",
    createdAt: new Date("2024-01-11"),
  },
  {
    id: "235698",
    ticketNumber: "#235698",
    title: "Cable suelto",
    category: "Alumbrado",
    subcategory: "Cableado",
    address: "SAN MARTIN 245 Barrio CENTRO",
    contact: "23445566",
    latitude: -33.3295,
    longitude: -60.2231,
    status: "open",
    priority: "high",
    agent: "alumbrado",
    createdAt: new Date("2024-01-09"),
  },
  {
    id: "235670",
    ticketNumber: "#235670",
    title: "Bache profundo",
    category: "Calles",
    subcategory: "Bacheo",
    address: "CORDOBA 890 Barrio ALBERDI",
    contact: "23445501",
    latitude: -33.3385,
    longitude: -60.2345,
    status: "open",
    priority: "high",
    agent: "vialidad",
    createdAt: new Date("2024-01-08"),
  },
  {
    id: "235671",
    ticketNumber: "#235671",
    title: "Pérdida de agua",
    category: "Agua",
    subcategory: "Cañerías",
    address: "DEAN FUNES 567 Barrio CENTRO",
    contact: "23445502",
    latitude: -33.3278,
    longitude: -60.2212,
    status: "open",
    priority: "high",
    agent: "obras sanitarias",
    createdAt: new Date("2024-01-07"),
  },
  {
    id: "235672",
    ticketNumber: "#235672",
    title: "Semáforo averiado",
    category: "Alumbrado",
    subcategory: "Semáforos",
    address: "AV COLON 1200 Barrio GENERAL PAZ",
    contact: "23445503",
    latitude: -33.3225,
    longitude: -60.2178,
    status: "open",
    priority: "medium",
    agent: "alumbrado",
    createdAt: new Date("2024-01-12"),
  },
  {
    id: "235673",
    ticketNumber: "#235673",
    title: "Árbol caído",
    category: "Espacios Verdes",
    subcategory: "Arbolado",
    address: "MENDOZA 450 Barrio NUEVA CORDOBA",
    contact: "23445504",
    latitude: -33.3412,
    longitude: -60.2376,
    status: "open",
    priority: "low",
    agent: "espacios verdes",
    createdAt: new Date("2024-01-13"),
  },
  {
    id: "235674",
    ticketNumber: "#235674",
    title: "Luminaria intermitente",
    category: "Alumbrado",
    subcategory: "Luminarias",
    address: "RIVADAVIA 789 Barrio CENTRO",
    contact: "23445505",
    latitude: -33.3308,
    longitude: -60.2251,
    status: "open",
    priority: "low",
    agent: "alumbrado",
    createdAt: new Date("2024-01-14"),
  },
  {
    id: "235675",
    ticketNumber: "#235675",
    title: "Fuga de gas reportada",
    category: "Gas",
    subcategory: "Fugas",
    address: "HUMBERTO PRIMO 234 Barrio SAN VICENTE",
    contact: "23445506",
    latitude: -33.3365,
    longitude: -60.2312,
    status: "open",
    priority: "high",
    agent: "gas",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "235676",
    ticketNumber: "#235676",
    title: "Contenedor de basura dañado",
    category: "Residuos",
    subcategory: "Contenedores",
    address: "TUCUMAN 567 Barrio CENTRO",
    contact: "23445507",
    latitude: -33.3322,
    longitude: -60.2275,
    status: "open",
    priority: "low",
    agent: "limpieza",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "235677",
    ticketNumber: "#235677",
    title: "Cartel de tránsito caído",
    category: "Señalización",
    subcategory: "Carteles",
    address: "AV VELEZ SARSFIELD 890 Barrio ALTA CORDOBA",
    contact: "23445508",
    latitude: -33.3248,
    longitude: -60.2195,
    status: "open",
    priority: "medium",
    agent: "vialidad",
    createdAt: new Date("2024-01-16"),
  },
  {
    id: "235678",
    ticketNumber: "#235678",
    title: "Cloaca tapada",
    category: "Agua",
    subcategory: "Cloacas",
    address: "CASEROS 123 Barrio GUEMES",
    contact: "23445509",
    latitude: -33.3262,
    longitude: -60.2188,
    status: "open",
    priority: "high",
    agent: "obras sanitarias",
    createdAt: new Date("2024-01-16"),
  },
  {
    id: "235679",
    ticketNumber: "#235679",
    title: "Poste con cables expuestos",
    category: "Alumbrado",
    subcategory: "Postes",
    address: "ENTRE RIOS 678 Barrio CENTRO",
    contact: "23445510",
    latitude: -33.3312,
    longitude: -60.2258,
    status: "open",
    priority: "high",
    agent: "alumbrado",
    createdAt: new Date("2024-01-17"),
  },
  {
    id: "235680",
    ticketNumber: "#235680",
    title: "Vereda rota",
    category: "Calles",
    subcategory: "Veredas",
    address: "LA RIOJA 345 Barrio ALBERDI",
    contact: "23445511",
    latitude: -33.3378,
    longitude: -60.2335,
    status: "open",
    priority: "medium",
    agent: "vialidad",
    createdAt: new Date("2024-01-17"),
  },
  {
    id: "235681",
    ticketNumber: "#235681",
    title: "Plaza con juegos dañados",
    category: "Espacios Verdes",
    subcategory: "Plazas",
    address: "PLAZA SAN MARTIN s/n Barrio CENTRO",
    contact: "23445512",
    latitude: -33.3305,
    longitude: -60.2245,
    status: "open",
    priority: "low",
    agent: "espacios verdes",
    createdAt: new Date("2024-01-18"),
  },
  {
    id: "235682",
    ticketNumber: "#235682",
    title: "Luminaria fundida",
    category: "Alumbrado",
    subcategory: "Luminarias",
    address: "BELGRANO 456 Barrio CENTRO",
    contact: "23445513",
    latitude: -33.3325,
    longitude: -60.2268,
    status: "open",
    priority: "medium",
    agent: "alumbrado",
    createdAt: new Date("2024-01-18"),
  },
  {
    id: "235683",
    ticketNumber: "#235683",
    title: "Alcantarilla sin tapa",
    category: "Calles",
    subcategory: "Alcantarillas",
    address: "JUJUY 789 Barrio GENERAL PAZ",
    contact: "23445514",
    latitude: -33.3235,
    longitude: -60.2165,
    status: "open",
    priority: "high",
    agent: "vialidad",
    createdAt: new Date("2024-01-19"),
  },
  {
    id: "235684",
    ticketNumber: "#235684",
    title: "Rama colgante sobre calle",
    category: "Espacios Verdes",
    subcategory: "Arbolado",
    address: "SANTA FE 234 Barrio NUEVA CORDOBA",
    contact: "23445515",
    latitude: -33.3425,
    longitude: -60.2388,
    status: "open",
    priority: "medium",
    agent: "espacios verdes",
    createdAt: new Date("2024-01-19"),
  },
  {
    id: "235685",
    ticketNumber: "#235685",
    title: "Falta de iluminación en cuadra",
    category: "Alumbrado",
    subcategory: "Luminarias",
    address: "SARMIENTO 890 Barrio CENTRO",
    contact: "23445516",
    latitude: -33.3298,
    longitude: -60.2238,
    status: "open",
    priority: "medium",
    agent: "alumbrado",
    createdAt: new Date("2024-01-20"),
  },
]

export const mockCrews: Crew[] = [
  { id: "c1", name: "Cuadrilla A - Zona Centro", available: true },
  { id: "c2", name: "Cuadrilla B - Zona Norte", available: true },
  { id: "c3", name: "Cuadrilla C - Zona Sur", available: false },
  { id: "c4", name: "Cuadrilla D - Emergencias", available: true },
]

export const mockRoutes: Route[] = [
  {
    id: "1",
    name: "Ruta Centro",
    totalAccepted: 13,
    tickets: [mockTickets[0], mockTickets[1], mockTickets[2]],
  },
  {
    id: "2",
    name: "Ruta Norte",
    totalAccepted: 8,
    tickets: [mockTickets[3], mockTickets[4]],
  },
]

export const mockMaterials: Material[] = [
  {
    id: "m1",
    code: "ALU-001",
    name: "Luminarias LED 50W",
    category: "Alumbrado",
    quantity: 0, // SIN STOCK - afecta Luminaria quemada, intermitente, fundida
    unit: "unidades",
    minStock: 20,
    location: "Depósito Central",
  },
  {
    id: "m2",
    code: "ALU-002",
    name: "Postes de hormigón 8m",
    category: "Alumbrado",
    quantity: 1, // BAJO STOCK - afecta Poste caído/torcido
    unit: "unidades",
    minStock: 5,
    location: "Depósito Central",
  },
  {
    id: "m3",
    code: "ALU-003",
    name: "Cable eléctrico (rollo 100m)",
    category: "Alumbrado",
    quantity: 8,
    unit: "rollos",
    minStock: 3,
    location: "Depósito Central",
  },
  {
    id: "m4",
    code: "CAL-001",
    name: "Asfalto en frío",
    category: "Calles",
    quantity: 350,
    unit: "kg",
    minStock: 100,
    location: "Depósito Vialidad",
  },
  {
    id: "m5",
    code: "CAL-002",
    name: "Cemento",
    category: "Calles",
    quantity: 280,
    unit: "bolsas",
    minStock: 50,
    location: "Depósito Vialidad",
  },
  {
    id: "m6",
    code: "SEN-001",
    name: "Señales de tránsito",
    category: "Señalización",
    quantity: 0, // SIN STOCK - afecta Cartel de tránsito caído
    unit: "unidades",
    minStock: 10,
    location: "Depósito Vialidad",
  },
  {
    id: "m7",
    code: "AGU-001",
    name: "Caños PVC 110mm",
    category: "Agua",
    quantity: 34,
    unit: "unidades",
    minStock: 15,
    location: "Depósito Sanitarias",
  },
  {
    id: "m8",
    code: "AGU-002",
    name: "Válvulas de paso",
    category: "Agua",
    quantity: 0, // SIN STOCK - afecta Pérdida de agua
    unit: "unidades",
    minStock: 8,
    location: "Depósito Sanitarias",
  },
  {
    id: "m9",
    code: "CAL-003",
    name: "Tapas de alcantarilla",
    category: "Calles",
    quantity: 0, // SIN STOCK - afecta Alcantarilla sin tapa
    unit: "unidades",
    minStock: 3,
    location: "Depósito Vialidad",
  },
  {
    id: "m10",
    code: "SEN-002",
    name: "Pintura vial blanca",
    category: "Señalización",
    quantity: 95,
    unit: "litros",
    minStock: 30,
    location: "Depósito Vialidad",
  },
  {
    id: "m11",
    code: "SEN-003",
    name: "Pintura vial amarilla",
    category: "Señalización",
    quantity: 67,
    unit: "litros",
    minStock: 30,
    location: "Depósito Vialidad",
  },
  {
    id: "m12",
    code: "RES-001",
    name: "Contenedores de basura",
    category: "Residuos",
    quantity: 8,
    unit: "unidades",
    minStock: 5,
    location: "Depósito Limpieza",
  },
]
