export const mockTickets = [
  {
    id: "1",
    ticketNumber: "TKT-001",
    title: "Luminaria apagada",
    category: "Alumbrado",
    subcategory: "Calle",
    address: "Av. Savio 123",
    contact: "Juan Pérez",
    latitude: -33.3317,
    longitude: -60.2264,
    status: "open",
    priority: "medium",
    agent: "Sistema",
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "2",
    ticketNumber: "TKT-002",
    title: "Bache profundo",
    category: "Calles",
    subcategory: "Bacheo",
    address: "Mitre 456",
    contact: "María García",
    latitude: -33.3342,
    longitude: -60.2298,
    status: "open",
    priority: "high",
    agent: "Call Center",
    createdAt: new Date("2024-01-11"),
  },
  {
    id: "3",
    ticketNumber: "TKT-003",
    title: "Cartel doblado",
    category: "Señalización",
    subcategory: "Cartelería",
    address: "Nación 789",
    contact: "Robert De Niro",
    latitude: -33.3295,
    longitude: -60.2231,
    status: "open",
    priority: "low",
    agent: "App Ciudadana",
    createdAt: new Date("2024-01-09"),
  },
  {
    id: "4",
    ticketNumber: "TKT-004",
    title: "Caño roto",
    category: "Agua",
    subcategory: "Pérdida",
    address: "Guardia Nacional 101",
    contact: "Lionel Messi",
    latitude: -33.3385,
    longitude: -60.2345,
    status: "open",
    priority: "high",
    agent: "Sistema",
    createdAt: new Date("2024-01-08"),
  },
  {
    id: "5",
    ticketNumber: "TKT-005",
    title: "Microbasural",
    category: "Residuos",
    subcategory: "Limpieza",
    address: "Sarmiento 202",
    contact: "Ricardo Darín",
    latitude: -33.3278,
    longitude: -60.2212,
    status: "open",
    priority: "medium",
    agent: "App Ciudadana",
    createdAt: new Date("2024-01-07"),
  },
  {
    id: "6",
    ticketNumber: "TKT-006",
    title: "Semáforo fuera de servicio",
    category: "Señalización",
    subcategory: "Semáforos",
    address: "9 de Julio y Belgrano",
    contact: "Mirtha Legrand",
    latitude: -33.3225,
    longitude: -60.2178,
    status: "open",
    priority: "high",
    agent: "Emsirze",
    createdAt: new Date("2024-01-12"),
  },
  {
    id: "7",
    ticketNumber: "TKT-007",
    title: "Poda correctiva urgente",
    category: "Espacios Verdes",
    subcategory: "Poda",
    address: "Pellegrini 567",
    contact: "Susana Giménez",
    latitude: -33.3412,
    longitude: -60.2376,
    status: "open",
    priority: "medium",
    agent: "Call Center",
    createdAt: new Date("2024-01-13"),
  },
  {
    id: "8",
    ticketNumber: "TKT-008",
    title: "Limpieza de sumidero",
    category: "Calles",
    subcategory: "Hidráulica",
    address: "Moreno 332",
    contact: "Margarita Barrientos",
    latitude: -33.3308,
    longitude: -60.2251,
    status: "open",
    priority: "low",
    agent: "App Ciudadana",
    createdAt: new Date("2024-01-14"),
  },
]

export const mockCrews = [
  { id: "crew-1", name: "Cuadrilla Alumbrado A", available: true },
  { id: "crew-2", name: "Cuadrilla Calles Sur", available: true },
  { id: "crew-3", name: "Cuadrilla Agua Central", available: false },
  { id: "crew-4", name: "Cuadrilla Residuos Norte", available: true },
]

export const mockRoutes = [
  {
    id: "route-1",
    name: "Ruta Centro Mañana",
    totalAccepted: 13,
    tickets: [mockTickets[0], mockTickets[1], mockTickets[2]],
  },
  {
    id: "route-2",
    name: "Ruta Sur Tarde",
    totalAccepted: 8,
    tickets: [mockTickets[3], mockTickets[4]],
  },
]

export const mockMaterials = [
  {
    id: "mat-1",
    code: "LAMP-LED-50W",
    name: "Lámpara LED 50W",
    category: "Alumbrado",
    quantity: 0,
    unit: "u",
    minStock: 20,
    location: "Depósito Central",
  },
  {
    id: "mat-2",
    code: "CABLE-SUB-2X4",
    name: "Cable Subterráneo 2x4",
    category: "Alumbrado",
    quantity: 1,
    unit: "m",
    minStock: 5,
    location: "Depósito Central",
  },
  {
    id: "mat-3",
    code: "MEZCLA-ASF-F",
    name: "Mezcla Asfáltica Fría",
    category: "Calles",
    quantity: 8,
    unit: "kg",
    minStock: 3,
    location: "Obrador Municipal",
  },
  {
    id: "mat-4",
    code: "TUBO-PVC-110",
    name: "Tubo PVC 110mm",
    category: "Agua",
    quantity: 350,
    unit: "m",
    minStock: 100,
    location: "Obrador Municipal",
  },
  {
    id: "mat-5",
    code: "CARTEL-PARE",
    name: "Señal Pare",
    category: "Señalización",
    quantity: 280,
    unit: "u",
    minStock: 50,
    location: "Depósito Vial",
  },
  {
    id: "mat-6",
    code: "BOLSAS-RES-G",
    name: "Bolsas Residuos Grandes",
    category: "Residuos",
    quantity: 0,
    unit: "u",
    minStock: 10,
    location: "Depósito Higiene",
  },
]
